/*
 * Shopping cart API
 * Manages a shopping cart
 *
 * The version of the OpenAPI document: 0.1.1
 * Contact: stephan.fuhrmann@ionos.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ionos.demo.shoppingcart.openapi.model;

import org.junit.Test;

/** Model tests for ShoppingCartItem */
public class ShoppingCartItemTest {
  private final ShoppingCartItem model = new ShoppingCartItem();

  /** Model tests for ShoppingCartItem */
  @Test
  public void testShoppingCartItem() {
    // TODO: test ShoppingCartItem
  }

  /** Test the property 'index' */
  @Test
  public void indexTest() {
    // TODO: test index
  }

  /** Test the property 'quantity' */
  @Test
  public void quantityTest() {
    // TODO: test quantity
  }

  /** Test the property 'itemAsin' */
  @Test
  public void itemAsinTest() {
    // TODO: test itemAsin
  }
}
