/*
 * Shopping cart API
 * Manages a shopping cart
 *
 * The version of the OpenAPI document: 0.1.1
 * Contact: stephan.fuhrmann@ionos.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ionos.demo.shoppingcart.openapi.model;

import org.junit.Test;

/** Model tests for ShoppingCartObject */
public class ShoppingCartObjectTest {
  private final ShoppingCartObject model = new ShoppingCartObject();

  /** Model tests for ShoppingCartObject */
  @Test
  public void testShoppingCartObject() {
    // TODO: test ShoppingCartObject
  }

  /** Test the property 'id' */
  @Test
  public void idTest() {
    // TODO: test id
  }

  /** Test the property 'owner' */
  @Test
  public void ownerTest() {
    // TODO: test owner
  }

  /** Test the property 'createdAt' */
  @Test
  public void createdAtTest() {
    // TODO: test createdAt
  }

  /** Test the property 'expiresAt' */
  @Test
  public void expiresAtTest() {
    // TODO: test expiresAt
  }
}
