---
artifactId: demo.daytime.client
groupId: com.ionos.network
artifactVersion: 1.0.0
hideGenerationTimestamp: true
developerEmail: stephan.fuhrmann@ionos.com
developerOrganizationUrl: https://www.ionos.com/
developerName: Stephan Fuhrmann
additionalProperties:
  invokerPackage: com.ionos.demo.daytime.openapi
  apiPackage: com.ionos.demo.daytime.openapi.api
  modelPackage: com.ionos.demo.daytime.openapi.model
  dateLibrary: java8
  java8: true
