openapi: 3.0.0
info:
  description: Tells the current date and time
  title: Daytime API
  version: 0.0.3
servers:
- description: Localhost
  url: http://localhost:8080/api/
paths:
  /daytime:
    get:
      description: |
        Gets the time of day.
      operationId: dateTime
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref:  "#/components/schemas/DateTimeObject"
          description: The daytime service response.
components:
  schemas:
    DateTimeObject:
      required:
        - date
      properties:
        date:
          type: string
          format: date-time
          description: The date and time in RFC 3339, section 5.6 format.
