openapi: 3.0.0
info:
  contact:
    email: stephan.fuhrmann@ionos.com
  description: Tells the current date and time
  license:
    name: GNU GENERAL PUBLIC LICENSE v3.0
    url: https://www.gnu.org/licenses/gpl-3.0.txt
  title: Daytime API
  version: 0.0.2
servers:
- description: Localhost
  url: http://localhost:8080/api/
paths:
  /daytime:
    get:
      description: |
        Gets the time of day.
      operationId: dateTime
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref:  "#/components/schemas/DateTimeObject"
          description: The daytime service response.
components:
  schemas:
    DateTimeObject:
      properties:
        date:
          type: string
          format: date-time
          description: The date and time in RFC 3339, section 5.6 format.
