/*
 * Daytime API
 * Tells the current date and time
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ionos.demo.daytime.openapi.api;

import com.ionos.demo.daytime.openapi.ApiException;
import com.ionos.demo.daytime.openapi.model.DateTimeObject;
import org.junit.Ignore;
import org.junit.Test;

/** API tests for DefaultApi */
@Ignore
public class DefaultApiTest {

  private final DefaultApi api = new DefaultApi();

  /**
   * Gets the time of day.
   *
   * @throws ApiException if the Api call fails
   */
  @Test
  public void dateTimeTest() throws ApiException {
    DateTimeObject response = api.dateTime();

    // TODO: test validations
  }
}
