/*
 * Daytime API
 * Tells the current date and time
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ionos.demo.daytime.openapi.model;

import org.junit.Test;

/** Model tests for DateTimeObject */
public class DateTimeObjectTest {
  private final DateTimeObject model = new DateTimeObject();

  /** Model tests for DateTimeObject */
  @Test
  public void testDateTimeObject() {
    // TODO: test DateTimeObject
  }

  /** Test the property 'date' */
  @Test
  public void dateTest() {
    // TODO: test date
  }
}
