/*
 * Daytime API
 * Tells the current date and time
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ionos.demo.daytime.openapi.api;

import com.google.gson.reflect.TypeToken;
import com.ionos.demo.daytime.openapi.ApiCallback;
import com.ionos.demo.daytime.openapi.ApiClient;
import com.ionos.demo.daytime.openapi.ApiException;
import com.ionos.demo.daytime.openapi.ApiResponse;
import com.ionos.demo.daytime.openapi.Configuration;
import com.ionos.demo.daytime.openapi.Pair;
import com.ionos.demo.daytime.openapi.model.DateTimeObject;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DefaultApi {
  private ApiClient localVarApiClient;

  public DefaultApi() {
    this(Configuration.getDefaultApiClient());
  }

  public DefaultApi(ApiClient apiClient) {
    this.localVarApiClient = apiClient;
  }

  public ApiClient getApiClient() {
    return localVarApiClient;
  }

  public void setApiClient(ApiClient apiClient) {
    this.localVarApiClient = apiClient;
  }

  /**
   * Build call for dateTime
   *
   * @param _callback Callback for upload/download progress
   * @return Call to execute
   * @throws ApiException If fail to serialize the request body object
   * @http.response.details
   *     <table summary="Response Details" border="1">
   * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
   * <tr><td> 200 </td><td> The daytime service response. </td><td>  -  </td></tr>
   * </table>
   */
  public okhttp3.Call dateTimeCall(final ApiCallback _callback) throws ApiException {
    Object localVarPostBody = null;

    // create path and map variables
    String localVarPath = "/daytime";

    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    final String[] localVarAccepts = {"application/json"};
    final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
    if (localVarAccept != null) {
      localVarHeaderParams.put("Accept", localVarAccept);
    }

    final String[] localVarContentTypes = {};

    final String localVarContentType =
        localVarApiClient.selectHeaderContentType(localVarContentTypes);
    localVarHeaderParams.put("Content-Type", localVarContentType);

    String[] localVarAuthNames = new String[] {};
    return localVarApiClient.buildCall(
        localVarPath,
        "GET",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAuthNames,
        _callback);
  }

  @SuppressWarnings("rawtypes")
  private okhttp3.Call dateTimeValidateBeforeCall(final ApiCallback _callback) throws ApiException {

    okhttp3.Call localVarCall = dateTimeCall(_callback);
    return localVarCall;
  }

  /**
   * Gets the time of day.
   *
   * @return DateTimeObject
   * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
   *     response body
   * @http.response.details
   *     <table summary="Response Details" border="1">
   * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
   * <tr><td> 200 </td><td> The daytime service response. </td><td>  -  </td></tr>
   * </table>
   */
  public DateTimeObject dateTime() throws ApiException {
    ApiResponse<DateTimeObject> localVarResp = dateTimeWithHttpInfo();
    return localVarResp.getData();
  }

  /**
   * Gets the time of day.
   *
   * @return ApiResponse&lt;DateTimeObject&gt;
   * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
   *     response body
   * @http.response.details
   *     <table summary="Response Details" border="1">
   * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
   * <tr><td> 200 </td><td> The daytime service response. </td><td>  -  </td></tr>
   * </table>
   */
  public ApiResponse<DateTimeObject> dateTimeWithHttpInfo() throws ApiException {
    okhttp3.Call localVarCall = dateTimeValidateBeforeCall(null);
    Type localVarReturnType = new TypeToken<DateTimeObject>() {}.getType();
    return localVarApiClient.execute(localVarCall, localVarReturnType);
  }

  /**
   * (asynchronously) Gets the time of day.
   *
   * @param _callback The callback to be executed when the API call finishes
   * @return The request call
   * @throws ApiException If fail to process the API call, e.g. serializing the request body object
   * @http.response.details
   *     <table summary="Response Details" border="1">
   * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
   * <tr><td> 200 </td><td> The daytime service response. </td><td>  -  </td></tr>
   * </table>
   */
  public okhttp3.Call dateTimeAsync(final ApiCallback<DateTimeObject> _callback)
      throws ApiException {

    okhttp3.Call localVarCall = dateTimeValidateBeforeCall(_callback);
    Type localVarReturnType = new TypeToken<DateTimeObject>() {}.getType();
    localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
    return localVarCall;
  }
}
