/*
 * Shopping cart API
 * Manages a shopping cart
 *
 * The version of the OpenAPI document: 0.1.1
 * Contact: stephan.fuhrmann@ionos.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ionos.demo.shoppingcart.openapi.api;

import com.ionos.demo.shoppingcart.openapi.ApiException;
import com.ionos.demo.shoppingcart.openapi.model.ShoppingCartItem;
import com.ionos.demo.shoppingcart.openapi.model.ShoppingCartObject;
import java.util.List;
import org.junit.Ignore;
import org.junit.Test;

/** API tests for MiddlewareApi */
@Ignore
public class MiddlewareApiTest {

  private final MiddlewareApi api = new MiddlewareApi();

  /**
   * Deletes the shopping cart.
   *
   * @throws ApiException if the Api call fails
   */
  @Test
  public void deleteCartByIdTest() throws ApiException {
    String cartId = null;
    ShoppingCartObject response = api.deleteCartById(cartId);

    // TODO: test validations
  }

  /**
   * Gets the shopping cart.
   *
   * @throws ApiException if the Api call fails
   */
  @Test
  public void getCartByIdTest() throws ApiException {
    String cartId = null;
    ShoppingCartObject response = api.getCartById(cartId);

    // TODO: test validations
  }

  /**
   * Gets the shopping cart items.
   *
   * @throws ApiException if the Api call fails
   */
  @Test
  public void getCartItemsTest() throws ApiException {
    String cartId = null;
    List<ShoppingCartItem> response = api.getCartItems(cartId);

    // TODO: test validations
  }

  /**
   * Lists all shopping carts.
   *
   * @throws ApiException if the Api call fails
   */
  @Test
  public void listCartsTest() throws ApiException {
    List<ShoppingCartObject> response = api.listCarts();

    // TODO: test validations
  }

  /**
   * Creates a new shopping cart.
   *
   * @throws ApiException if the Api call fails
   */
  @Test
  public void newCartTest() throws ApiException {
    ShoppingCartObject shoppingCartObject = null;
    ShoppingCartObject response = api.newCart(shoppingCartObject);

    // TODO: test validations
  }

  /**
   * Updates the shopping cart items.
   *
   * @throws ApiException if the Api call fails
   */
  @Test
  public void putCartItemsTest() throws ApiException {
    String cartId = null;
    List<ShoppingCartItem> response = api.putCartItems(cartId);

    // TODO: test validations
  }
}
